"""Render detailed matrices from the current JSON, keeping presentation in sync with corrections."""
from pathlib import Path
import json,html
ROOT=Path(__file__).resolve().parent.parent/'docs'
E=lambda x:html.escape(str(x),quote=True)
def text(x):return json.dumps(x,ensure_ascii=False) if isinstance(x,dict) else str(x)
for model,label in [('luna','GPT-6-Luna'),('sol','GPT-6.1-Sol')]:
 data=json.loads((ROOT/model/'matrix.json').read_text()); dims=data['dimensions']
 css='''*{box-sizing:border-box}body{margin:0;background:#f6f8fb;color:#18283d;font:15px/1.6 system-ui,sans-serif}main{max-width:1800px;margin:auto;padding:32px 26px}a{color:#165b91}nav{display:flex;flex-wrap:wrap;gap:18px;justify-content:space-between;margin-bottom:28px}.views a{padding:8px 15px}.active{background:#e5eaf0;border-radius:5px;font-weight:700}h1{font-size:clamp(26px,3vw,40px);line-height:1.2}.notice{padding:18px 22px;background:#eaf2ee;border-left:3px solid #377761;margin:20px 0}.tools{margin:22px 0}input{padding:10px 12px;border:1px solid #bbb;border-radius:5px;font:inherit;width:320px;max-width:100%}.matrix-wrap{overflow:auto;max-height:78vh;background:white;border:1px solid #ccc;border-radius:5px}table{width:100%;min-width:1800px;border-collapse:separate;border-spacing:0;table-layout:fixed}th,td{padding:18px;vertical-align:top;text-align:left;border-bottom:1px solid #ddd;border-right:1px solid #ddd}thead th{position:sticky;top:0;background:#253e56;color:white;z-index:3}thead th:first-child{width:270px;left:0;z-index:4}tbody th{width:270px;position:sticky;left:0;background:#f2f5f8;z-index:2}.badge{font-size:11px;font-weight:700;color:#236149;background:#e5f2e9;padding:3px 6px;display:inline-block}.badge.not_measured,.badge.not_reported{background:#eceff3;color:#596675}.finding{font-size:14px;margin-top:10px}.sources{font-size:12px;padding-left:18px}.sources li{margin:8px 0}details{font-size:13px;font-weight:400;margin-top:16px}summary{cursor:pointer;color:#165b91}small{display:block;font-weight:400;margin-top:8px;color:#536573}dt{font-weight:650;margin-top:10px}dd{margin:3px 0;overflow-wrap:anywhere}a:focus-visible,input:focus-visible,summary:focus-visible{outline:3px solid #dcad41;outline-offset:4px}[hidden]{display:none!important}@media print{.matrix-wrap{overflow:visible;max-height:none}th{position:static!important}table{min-width:0}th,td{font-size:9px;padding:6px}}'''
 h=[f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(label)} — Advanced evidence matrix</title><style>{css}</style></head><body><main><nav><a href="../index.html">Research overview</a><a href="../comparison.html">Compare baseline, Luna and Sol</a><span class="views"><a href="matrix.html">Simple</a><a class="active" aria-current="page" href="matrix.advanced.html">Advanced</a></span></nav><h1>Evidence matrix: 27 studies × 6 finding dimensions</h1><div class="notice"><strong>Evidence extracted by {E(label)} · Extra High.</strong> GPT-4 and other names in findings identify the models tested by the original papers. These are source re-extractions, not new peer-review experiments evaluating {E(label)}.</div><p>Full findings, evidence statuses, source locators and study metadata. “Verified” denotes a checked source extraction, not independent reproduction of the experiment.</p><div class="tools"><input id="search" type="search" aria-label="Find a study" placeholder="Find a study or finding…"><span id="count" aria-live="polite">27 studies</span></div><div class="matrix-wrap" tabindex="0" role="region" aria-label="Detailed evidence matrix"><table><thead><tr><th scope="col">Study / primary source</th>']
 h.extend(f'<th scope="col">{E(d.replace("_"," ").title())}</th>' for d in dims);h.append('</tr></thead><tbody>')
 for r in sorted(data['rows'],key=lambda x:(x['publication_date'],x['candidate_id'])):
  citation=r['citation']; title=citation['title'] if isinstance(citation,dict) else citation
  h.append(f'<tr><th scope="row"><a href="{E(r["source_url"])}">#{r["candidate_id"]} {E(title)}</a><small>{E(r["publication_date"])} · {E(r["publication_status"])}</small><details><summary>Study context and source version</summary><dl>')
  for k,v in [('Evidence extraction model',data['extraction_model']),('Models tested in this study',r['evaluated_models']),('Design and sample',r['design_and_sample']),('Source version',text(r['source_version'])),('Identity or scope note',r['identity_or_scope_note'])]:
   if v:h.append(f'<dt>{E(k)}</dt><dd>{E(v)}</dd>')
  h.append('</dl></details></th>')
  for d in dims:
   c=r['dimensions'][d];h.append(f'<td><span class="badge {E(c["status"])}">{E(c["status"].replace("_"," "))}</span><div class="finding">{E(c["finding"])}</div><ul class="sources">')
   for q in c['citations']:h.append(f'<li><a href="{E(q["url"])}">{E(q["location"])}</a></li>')
   h.append('</ul></td>')
  h.append('</tr>')
 h.append('''</tbody></table></div><p><a href="matrix.json">JSON</a> · <a href="matrix.md">Markdown</a> · <a href="corrections.md">Correction log</a></p></main><script>const rows=[...document.querySelectorAll('tbody tr')];document.querySelector('#search').addEventListener('input',e=>{let n=0,q=e.target.value.toLowerCase().trim();for(const r of rows){r.hidden=!r.textContent.toLowerCase().includes(q);if(!r.hidden)n++;}document.querySelector('#count').textContent=n+' of 27 studies';});</script></body></html>''')
 (ROOT/model/'matrix.advanced.html').write_text(''.join(h))
 print(label, len(data['rows']),'detailed rows rendered from current JSON')
